/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hubs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Hubs
         * @description List every configured hub (from DEVICE_TOKENS) plus any hub seen since startup,
         *     with its connection state.
         */
        get: operations["list_hubs_api_hubs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hubs/{hub_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Hub
         * @description Get hub details.
         */
        get: operations["get_hub_api_hubs__hub_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hubs/{hub_id}/commands/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Close Connection Command
         * @description Send close connection command to hub.
         */
        post: operations["send_close_connection_command_api_hubs__hub_id__commands_close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hubs/{hub_id}/commands/flash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Flash Firmware Command
         * @description Send flash firmware command to hub.
         */
        post: operations["send_flash_firmware_command_api_hubs__hub_id__commands_flash_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hubs/{hub_id}/commands/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Restart Device Command
         * @description Send restart device command to hub.
         */
        post: operations["send_restart_device_command_api_hubs__hub_id__commands_restart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hubs/{hub_id}/commands/write": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Serial Write Command
         * @description Send serial write command to hub.
         */
        post: operations["send_serial_write_command_api_hubs__hub_id__commands_write_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hubs/{hub_id}/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Connections
         * @description Get open serial connections for a hub. Offline hubs report none.
         */
        get: operations["get_connections_api_hubs__hub_id__connections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hubs/{hub_id}/ports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ports
         * @description Get ports for a hub. Offline hubs report no ports.
         */
        get: operations["get_ports_api_hubs__hub_id__ports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hubs/{hub_id}/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Telemetry
         * @description Get recent telemetry for a hub (kept after the hub disconnects).
         */
        get: operations["get_telemetry_api_hubs__hub_id__telemetry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Login with NetID and the team password.
         *
         *     Accepts either JSON {"username": "..", "password": ".."} or form data (x-www-form-urlencoded).
         *
         *     Returns JWT access token.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login-viewer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login Viewer
         * @description Login as a viewer with read-only access.
         *
         *     Returns JWT access token with viewer role.
         */
        post: operations["login_viewer_auth_login_viewer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Get current user information.
         */
        get: operations["get_me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health check endpoint.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BoardProfileInfo
         * @description Board resolved by the hub from the USB VID/PID registry (config/boards.yaml).
         */
        BoardProfileInfo: {
            /** Artifacts */
            artifacts?: string[];
            /** Fqbn */
            fqbn?: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * CloseConnectionRequest
         * @description Request to close a connection.
         */
        CloseConnectionRequest: {
            /**
             * Portid
             * @description Target port ID
             */
            portId: string;
            /**
             * Priority
             * @description Command priority
             * @default 1
             */
            priority?: number;
        };
        /**
         * Command
         * @description Command details.
         */
        Command: {
            /** Commandid */
            commandId: string;
            /** Commandtype */
            commandType: string;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Portid */
            portId: string;
            /**
             * Priority
             * @default 5
             */
            priority: number;
        };
        /**
         * CommandEnvelope
         * @description Command envelope sent to hub.
         */
        CommandEnvelope: {
            command: components["schemas"]["Command"];
            /**
             * Type
             * @default command
             * @constant
             */
            type: "command";
        };
        /** ConnectedMessage */
        ConnectedMessage: {
            /** Message */
            message: string;
            /** Timestamp */
            timestamp: string;
            /**
             * Type
             * @default connected
             * @constant
             */
            type: "connected";
        };
        /**
         * ConnectionInfo
         * @description Connection information.
         */
        ConnectionInfo: {
            /** Baud Rate */
            baud_rate: number;
            /** Bytes Read */
            bytes_read: number;
            /** Bytes Written */
            bytes_written: number;
            /** Connected At */
            connected_at?: string | null;
            /** Port Id */
            port_id: string;
            /** Session Id */
            session_id: string;
            /** Status */
            status: string;
        };
        /**
         * ConnectionListResponse
         * @description List of connections.
         */
        ConnectionListResponse: {
            /** Connections */
            connections: components["schemas"]["ConnectionInfo"][];
            /** Count */
            count: number;
            /** Hubid */
            hubId: string;
        };
        /** DeviceEventBroadcast */
        DeviceEventBroadcast: {
            /** Event */
            event: string;
            /** Hubid */
            hubId: string;
            /** Portid */
            portId: string;
            /** Timestamp */
            timestamp: string;
            /**
             * Type
             * @default device_event
             * @constant
             */
            type: "device_event";
        };
        /**
         * DeviceEventMessage
         * @description Device event from hub.
         */
        DeviceEventMessage: {
            /**
             * Deviceinfo
             * @default null
             */
            deviceInfo?: {
                [key: string]: unknown;
            } | null;
            /** Eventtype */
            eventType: string;
            /** Hubid */
            hubId: string;
            /** Portid */
            portId: string;
            /** Timestamp */
            timestamp: string;
            /**
             * Type
             * @default device_event
             */
            type?: string;
        };
        /** DeviceSubscription */
        DeviceSubscription: {
            /** Hubid */
            hubId: string;
            /** Portid */
            portId: string;
        };
        /**
         * FlashFirmwareRequest
         * @description Request to send flash firmware command.
         */
        FlashFirmwareRequest: {
            /**
             * Artifactformat
             * @description Firmware format; inferred as ino/hex when omitted (older hubs only accept those)
             */
            artifactFormat?: ("ino" | "hex" | "bin" | "elf") | null;
            /**
             * Boardfqbn
             * @description Board FQBN (required for .ino source)
             */
            boardFqbn?: string | null;
            /**
             * Boardprofile
             * @description Board profile id from the hub's board registry
             */
            boardProfile?: string | null;
            /**
             * Firmwaredata
             * @description Base64 encoded firmware (.ino source, .hex, .bin or .elf)
             */
            firmwareData: string;
            /**
             * Portid
             * @description Target port ID
             */
            portId: string;
            /**
             * Priority
             * @description Command priority
             * @default 3
             */
            priority?: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthBroadcast */
        HealthBroadcast: {
            /**
             * Cpu Percent
             * @default null
             */
            cpu_percent: number | null;
            /**
             * Disk Percent
             * @default null
             */
            disk_percent: number | null;
            /** Hubid */
            hubId: string;
            /**
             * Memory Percent
             * @default null
             */
            memory_percent: number | null;
            /**
             * Mode
             * @default null
             */
            mode: string | null;
            /** Timestamp */
            timestamp: string;
            /**
             * Type
             * @default health
             * @constant
             */
            type: "health";
            /**
             * Uplink
             * @default null
             */
            uplink: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * HealthMessage
         * @description Health metrics from hub.
         */
        HealthMessage: {
            /** Errors */
            errors: {
                [key: string]: unknown;
            };
            /** Hubid */
            hubId: string;
            /**
             * Profile
             * @default null
             */
            profile?: {
                [key: string]: unknown;
            } | null;
            /** Service */
            service: {
                [key: string]: unknown;
            };
            /** System */
            system: {
                [key: string]: unknown;
            };
            /** Timestamp */
            timestamp: string;
            /**
             * Type
             * @default health
             */
            type?: string;
            /**
             * Uplink
             * @default null
             */
            uplink?: {
                [key: string]: unknown;
            } | null;
            /** Uptime Seconds */
            uptime_seconds: number;
        };
        /** HubConnectedAck */
        HubConnectedAck: {
            /** Hubid */
            hubId: string;
            /** Timestamp */
            timestamp: string;
            /**
             * Type
             * @default hub_connected
             * @constant
             */
            type: "hub_connected";
        };
        /**
         * HubHandshake
         * @description Hub connection handshake message.
         */
        HubHandshake: {
            /** Capabilities */
            capabilities?: string[];
            /** Devicetoken */
            deviceToken: string;
            /** Hubid */
            hubId: string;
            /** @default null */
            profile?: components["schemas"]["HubProfile"] | null;
            /** Timestamp */
            timestamp: string;
            /**
             * Type
             * @default hub_connect
             */
            type?: string;
            /**
             * Version
             * @default 1.0.0
             */
            version?: string;
        };
        /**
         * HubInfo
         * @description Hub information.
         */
        HubInfo: {
            /** Capabilities */
            capabilities?: string[];
            /** Connected */
            connected: boolean;
            /** Connectedat */
            connectedAt?: string | null;
            /** Hubid */
            hubId: string;
            /** Lastseen */
            lastSeen?: string | null;
            profile?: components["schemas"]["HubProfile"] | null;
            /** Version */
            version?: string | null;
        };
        /**
         * HubProfile
         * @description What kind of hub this is, as reported in the handshake.
         */
        HubProfile: {
            /**
             * Mode
             * @default bench
             */
            mode?: string;
            /** Name */
            name?: string | null;
            /** Uplink */
            uplink?: string | null;
        };
        /**
         * HubStatusBroadcast
         * @description Sent to every browser when a hub connects or disconnects.
         */
        HubStatusBroadcast: {
            /** Connected */
            connected: boolean;
            /** Hubid */
            hubId: string;
            /** Timestamp */
            timestamp: string;
            /**
             * Type
             * @default hub_status
             * @constant
             */
            type: "hub_status";
        };
        /** PingMessage */
        PingMessage: {
            /** Timestamp */
            timestamp: string;
            /**
             * Type
             * @default ping
             * @constant
             */
            type: "ping";
        };
        /** PongMessage */
        PongMessage: {
            /**
             * Timestamp
             * @default null
             */
            timestamp?: string | null;
            /**
             * Type
             * @default pong
             * @constant
             */
            type?: "pong";
        };
        /**
         * PortInfo
         * @description Port information.
         */
        PortInfo: {
            board_profile?: components["schemas"]["BoardProfileInfo"] | null;
            /** Description */
            description?: string | null;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Port */
            port: string;
            /** Port Id */
            port_id: string;
            /** Product Id */
            product_id?: string | null;
            /** Serial Number */
            serial_number?: string | null;
            /** Vendor Id */
            vendor_id?: string | null;
        };
        /**
         * PortListResponse
         * @description List of ports.
         */
        PortListResponse: {
            /** Count */
            count: number;
            /** Hubid */
            hubId: string;
            /** Ports */
            ports: components["schemas"]["PortInfo"][];
        };
        /**
         * RestartDeviceRequest
         * @description Request to send restart device command.
         */
        RestartDeviceRequest: {
            /**
             * Portid
             * @description Target port ID
             */
            portId: string;
            /**
             * Priority
             * @description Command priority
             * @default 2
             */
            priority?: number;
        };
        /**
         * SerialWriteRequest
         * @description Request to send serial write command.
         */
        SerialWriteRequest: {
            /**
             * Data
             * @description Data to write
             */
            data: string;
            /**
             * Encoding
             * @description Data encoding
             * @default utf-8
             */
            encoding?: string;
            /**
             * Portid
             * @description Target port ID
             */
            portId: string;
            /**
             * Priority
             * @description Command priority
             * @default 5
             */
            priority?: number;
        };
        /** SubscribeMessage */
        SubscribeMessage: {
            /** Subscriptions */
            subscriptions: components["schemas"]["DeviceSubscription"][];
            /**
             * Type
             * @default subscribe
             * @constant
             */
            type?: "subscribe";
        };
        /** SubscriptionState */
        SubscriptionState: {
            /** Hubid */
            hubId: string;
            /** Portid */
            portId: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "inactive";
        };
        /** SubscriptionStatusMessage */
        SubscriptionStatusMessage: {
            /** Subscriptions */
            subscriptions: components["schemas"]["SubscriptionState"][];
            /** Timestamp */
            timestamp: string;
            /**
             * Type
             * @default subscription_status
             * @constant
             */
            type: "subscription_status";
        };
        /** TaskStatusBroadcast */
        TaskStatusBroadcast: {
            /**
             * Commandtype
             * @default null
             */
            commandType: string | null;
            /**
             * Error
             * @default null
             */
            error: string | null;
            /** Hubid */
            hubId: string;
            /**
             * Portid
             * @default null
             */
            portId: string | null;
            /**
             * Progress
             * @default null
             */
            progress: number | null;
            /**
             * Result
             * @default null
             */
            result: {
                [key: string]: unknown;
            } | null;
            /** Status */
            status: string;
            /** Task Id */
            task_id: string;
            /** Timestamp */
            timestamp: string;
            /**
             * Type
             * @default task_status
             * @constant
             */
            type: "task_status";
        };
        /**
         * TaskStatusMessage
         * @description Task status update from hub.
         */
        TaskStatusMessage: {
            /**
             * Commandtype
             * @default null
             */
            commandType?: string | null;
            /**
             * Error
             * @default null
             */
            error?: string | null;
            /** Hubid */
            hubId: string;
            /**
             * Portid
             * @default null
             */
            portId?: string | null;
            /**
             * Progress
             * @default null
             */
            progress?: number | null;
            /**
             * Result
             * @default null
             */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Status */
            status: string;
            /** Taskid */
            taskId: string;
            /** Timestamp */
            timestamp: string;
            /**
             * Type
             * @default task_status
             */
            type?: string;
        };
        /**
         * TaskStatusResponse
         * @description Task status response.
         */
        TaskStatusResponse: {
            /** Command Type */
            command_type?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Error */
            error?: string | null;
            /** Hub Id */
            hub_id?: string | null;
            /** Port Id */
            port_id?: string | null;
            /** Priority */
            priority?: number | null;
            /** Progress */
            progress?: number | null;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Status */
            status: string;
            /** Task Id */
            task_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /**
         * TelemetryEntry
         * @description Telemetry data entry.
         */
        TelemetryEntry: {
            /** Data */
            data: string;
            /** Datasizebytes */
            dataSizeBytes: number;
            /** Portid */
            portId: string;
            /** Sessionid */
            sessionId: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /**
         * TelemetryListResponse
         * @description List of telemetry entries.
         */
        TelemetryListResponse: {
            /** Count */
            count: number;
            /** Hubid */
            hubId: string;
            /** Telemetry */
            telemetry: components["schemas"]["TelemetryEntry"][];
            /** Totalbytes */
            totalBytes: number;
        };
        /**
         * TelemetryMessage
         * @description Telemetry data from hub.
         */
        TelemetryMessage: {
            /** Data */
            data: string;
            /** Hubid */
            hubId: string;
            /** Portid */
            portId: string;
            /** Sessionid */
            sessionId: string;
            /** Timestamp */
            timestamp: string;
            /**
             * Type
             * @default telemetry
             */
            type?: string;
        };
        /** TelemetryStreamMessage */
        TelemetryStreamMessage: {
            /** Data */
            data: string;
            /** Datasizebytes */
            dataSizeBytes: number;
            /** Hubid */
            hubId: string;
            /** Portid */
            portId: string;
            /** Sessionid */
            sessionId: string;
            /** Timestamp */
            timestamp: string;
            /**
             * Type
             * @default telemetry_stream
             * @constant
             */
            type: "telemetry_stream";
        };
        /**
         * TokenResponse
         * @description JWT token response.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type?: string;
        };
        /** UnsubscribeMessage */
        UnsubscribeMessage: {
            /** Subscriptions */
            subscriptions: components["schemas"]["DeviceSubscription"][];
            /**
             * Type
             * @default unsubscribe
             * @constant
             */
            type?: "unsubscribe";
        };
        /**
         * UserInfo
         * @description User information.
         */
        UserInfo: {
            /** Email */
            email?: string | null;
            /** Full Name */
            full_name?: string | null;
            /** Role */
            role?: string | null;
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_hubs_api_hubs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HubInfo"][];
                };
            };
        };
    };
    get_hub_api_hubs__hub_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hub_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HubInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_close_connection_command_api_hubs__hub_id__commands_close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hub_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloseConnectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_flash_firmware_command_api_hubs__hub_id__commands_flash_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hub_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlashFirmwareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_restart_device_command_api_hubs__hub_id__commands_restart_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hub_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestartDeviceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_serial_write_command_api_hubs__hub_id__commands_write_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hub_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SerialWriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_connections_api_hubs__hub_id__connections_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hub_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ports_api_hubs__hub_id__ports_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hub_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_telemetry_api_hubs__hub_id__telemetry_get: {
        parameters: {
            query?: {
                limit?: number | null;
            };
            header?: never;
            path: {
                hub_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetryListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    login_viewer_auth_login_viewer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    get_me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfo"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
